# Generated by Django 4.0.5 on 2022-06-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=25)),
                ('account_number', models.CharField(max_length=25)),
                ('meta_trader', models.CharField(choices=[('mt4', 'mt4'), ('mt5', 'mt5')], max_length=10)),
                ('account_type', models.CharField(max_length=25)),
                ('server_name', models.CharField(max_length=30)),
                ('trading_password', models.CharField(max_length=25)),
                ('investor_password', models.CharField(max_length=25)),
                ('leverage', models.IntegerField()),
                ('currency_unit', models.CharField(choices=[('cent', 'cent'), ('dollar', 'dollar')], max_length=20)),
                ('equity', models.FloatField()),
                ('backup_equity', models.FloatField()),
                ('minimun_equity', models.FloatField()),
                ('TDP_share', models.FloatField()),
                ('first_referer_name', models.CharField(max_length=50)),
                ('first_referer_percent', models.FloatField()),
                ('second_referer_name', models.CharField(max_length=50)),
                ('second_referer_percent', models.FloatField()),
                ('third_referer_name', models.CharField(max_length=50)),
                ('third_referer_percent', models.FloatField()),
            ],
            options={
                'db_table': 'account_master',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('mobile_number', models.IntegerField()),
                ('aadhar_card', models.IntegerField()),
                ('pan', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='virtual_private_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('vps_name', models.CharField(max_length=25)),
                ('vps_plan', models.CharField(max_length=50)),
                ('vps_id', models.CharField(max_length=25)),
                ('vps_username', models.CharField(max_length=25)),
                ('vps_password', models.CharField(max_length=25)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'vps',
            },
        ),
        migrations.CreateModel(
            name='profit_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(unique=True)),
                ('profit', models.FloatField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.account_master')),
            ],
            options={
                'db_table': 'profit_details',
            },
        ),
        migrations.CreateModel(
            name='profit_claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_profit', models.FloatField()),
                ('exchange_rate', models.FloatField()),
                ('total_profit_in_INR', models.FloatField()),
                ('commission_rate', models.FloatField()),
                ('our_share', models.FloatField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.account_master')),
            ],
            options={
                'db_table': 'profit_claim',
            },
        ),
        migrations.CreateModel(
            name='claim_settled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('received_date', models.DateField()),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.profit_claim')),
            ],
            options={
                'db_table': 'claim_settled',
            },
        ),
        migrations.AddField(
            model_name='account_master',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client'),
        ),
        migrations.AddField(
            model_name='account_master',
            name='vps_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.virtual_private_server'),
        ),
    ]
