# Generated by Django 4.0.5 on 2022-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_claim',
            name='claim_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
