# Generated by Django 4.0.5 on 2022-06-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='aadhar_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
