# Generated by Django 4.0.5 on 2022-06-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_aadhar_card_alter_client_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_master',
            name='first_referer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='second_referer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='third_referer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
