# Generated by Django 4.0.5 on 2022-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_profit_claim_claim_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_master',
            name='first_referer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Referer Name'),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='first_referer_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='First Referer (%)'),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='second_referer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Referer Name'),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='third_referer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Referer Name'),
        ),
    ]
