# Generated by Django 4.0.5 on 2022-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_account_master_first_referer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_claim',
            name='received',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='profit_claim',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
