# Generated by Django 4.0.5 on 2022-06-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_account_master_first_referer_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_master',
            name='first_referer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='first_referer_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='second_referer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='second_referer_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='third_referer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account_master',
            name='third_referer_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
