# Generated by Django 4.0.5 on 2022-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_account_master_first_referer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim_settled',
            name='claim_settled_in',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=15),
        ),
        migrations.AddField(
            model_name='claim_settled',
            name='settlement_method',
            field=models.CharField(default='transfered', max_length=255),
        ),
        migrations.AddField(
            model_name='profit_claim',
            name='our_share_in_INR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit_claim',
            name='commission_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit_claim',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit_claim',
            name='our_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit_claim',
            name='total_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profit_claim',
            name='total_profit_in_INR',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
